import { AbstractStorageService } from '../../../core/AbstractStorageService';
import { Result, Page } from '../../../core/types';
import { AppEvents, eventEmitter } from '../../../core/events';
import { Video, VideoType, VideoFilter, VideoStats, VideoComment } from '../types';

const MOCK_VIDEOS: Partial<Video>[] = [
  {
    id: 'v1',
    title: 'Neural Network Dreaming',
    description: 'Watch AI visualize its own thoughts in real-time',
    author: 'Omni Vision',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omni',
    thumbnail: 'https://picsum.photos/400/600?random=101',
    url: 'https://example.com/video1.mp4',
    duration: 45,
    likes: 102000,
    views: 580000,
    comments: 882,
    shares: 1200,
    type: 'neural',
    hasLiked: false,
    hasCollected: false,
    tags: ['AI', 'Neural', 'Generative']
  },
  {
    id: 'v2',
    title: 'Data Stream Flow',
    description: 'Visualizing big data in motion',
    author: 'Tech Core',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tech',
    thumbnail: 'https://picsum.photos/400/600?random=102',
    url: 'https://example.com/video2.mp4',
    duration: 32,
    likes: 56000,
    views: 320000,
    comments: 341,
    shares: 560,
    type: 'matrix',
    hasLiked: false,
    hasCollected: false,
    tags: ['Matrix', 'Data', 'Tech']
  },
  {
    id: 'v3',
    title: 'Aurora AI',
    description: 'Northern lights generated by artificial intelligence',
    author: 'Nature Bot',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nature',
    thumbnail: 'https://picsum.photos/400/600?random=103',
    url: 'https://example.com/video3.mp4',
    duration: 58,
    likes: 218000,
    views: 1200000,
    comments: 1200,
    shares: 3400,
    type: 'aurora',
    hasLiked: true,
    hasCollected: false,
    tags: ['Aurora', 'Nature', 'Beautiful']
  },
  {
    id: 'v4',
    title: 'Cyberpunk City',
    description: 'A journey through futuristic cityscapes',
    author: 'Creative AI',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Creative',
    thumbnail: 'https://picsum.photos/400/600?random=104',
    url: 'https://example.com/video4.mp4',
    duration: 67,
    likes: 89000,
    views: 450000,
    comments: 556,
    shares: 890,
    type: 'cyber',
    hasLiked: false,
    hasCollected: true,
    tags: ['Cyberpunk', 'City', 'Future']
  },
  {
    id: 'v5',
    title: 'Forest Meditation',
    description: 'Relax with AI-generated forest scenes',
    author: 'Zen Master',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zen',
    thumbnail: 'https://picsum.photos/400/600?random=105',
    url: 'https://example.com/video5.mp4',
    duration: 120,
    likes: 45000,
    views: 280000,
    comments: 234,
    shares: 450,
    type: 'nature',
    hasLiked: false,
    hasCollected: false,
    tags: ['Nature', 'Relax', 'Meditation']
  },
  {
    id: 'v6',
    title: 'System Core',
    description: 'Inside the digital infrastructure',
    author: 'Admin',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    thumbnail: 'https://picsum.photos/400/600?random=106',
    url: 'https://example.com/video6.mp4',
    duration: 41,
    likes: 999900,
    views: 5000000,
    comments: 9999,
    shares: 15000,
    type: 'matrix',
    hasLiked: false,
    hasCollected: false,
    tags: ['System', 'Core', 'Tech']
  }
];

class VideoServiceImpl extends AbstractStorageService<Video> {
  constructor() {
    super('sys_short_videos_pc_v1');
  }

  protected async onInitialize() {
    const list = await this.loadData();
    if (list.length === 0) {
      const now = Date.now();
      for (const v of MOCK_VIDEOS) {
        await this.saveItem({ ...v, createTime: now, updateTime: now } as Video);
      }
    }
  }

  async getVideos(filter: VideoFilter = {}, page: number = 1, size: number = 12): Promise<Result<Page<Video>>> {
    let list = await this.loadData();

    if (filter.type) {
      list = list.filter(v => v.type === filter.type);
    }

    if (filter.search) {
      const lowerSearch = filter.search.toLowerCase();
      list = list.filter(v => 
        v.title.toLowerCase().includes(lowerSearch) ||
        v.description?.toLowerCase().includes(lowerSearch) ||
        v.tags.some(tag => tag.toLowerCase().includes(lowerSearch))
      );
    }

    // Sort by popularity (likes + views)
    list.sort((a, b) => (b.likes + b.views * 0.1) - (a.likes + a.views * 0.1));

    const total = list.length;
    const start = (page - 1) * size;
    const content = list.slice(start, start + size);

    return {
      success: true,
      data: {
        content,
        total,
        page,
        size,
        totalPages: Math.ceil(total / size)
      }
    };
  }

  async getVideoById(id: string): Promise<Result<Video | null>> {
    return await this.getById(id);
  }

  async toggleLike(id: string): Promise<Result<void>> {
    const { data: video } = await this.getById(id);
    if (video) {
      video.hasLiked = !video.hasLiked;
      video.likes += video.hasLiked ? 1 : -1;
      await this.saveItem(video);
      eventEmitter.emit(AppEvents.DATA_UPDATED, { key: this.storageKey });
    }
    return { success: true };
  }

  async toggleCollect(id: string): Promise<Result<void>> {
    const { data: video } = await this.getById(id);
    if (video) {
      video.hasCollected = !video.hasCollected;
      await this.saveItem(video);
      eventEmitter.emit(AppEvents.DATA_UPDATED, { key: this.storageKey });
    }
    return { success: true };
  }

  async incrementViews(id: string): Promise<Result<void>> {
    const { data: video } = await this.getById(id);
    if (video) {
      video.views++;
      await this.saveItem(video);
    }
    return { success: true };
  }

  async getComments(videoId: string): Promise<Result<VideoComment[]>> {
    // Mock comments
    const comments: VideoComment[] = [
      {
        id: 'c1',
        videoId,
        userId: 'u1',
        userName: 'Tech Enthusiast',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tech',
        content: 'This is absolutely amazing! The AI generation is so smooth.',
        likes: 234,
        createTime: Date.now() - 3600000
      },
      {
        id: 'c2',
        videoId,
        userId: 'u2',
        userName: 'Creative Soul',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Creative',
        content: 'Love the visual effects! Can you share the prompt?',
        likes: 89,
        createTime: Date.now() - 7200000
      },
      {
        id: 'c3',
        videoId,
        userId: 'u3',
        userName: 'AI Explorer',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AI',
        content: 'The future of content creation is here!',
        likes: 156,
        createTime: Date.now() - 10800000
      }
    ];
    return { success: true, data: comments };
  }

  async getStats(): Promise<Result<VideoStats>> {
    const list = await this.loadData();
    
    const stats: VideoStats = {
      totalVideos: list.length,
      totalViews: list.reduce((sum, v) => sum + v.views, 0),
      totalLikes: list.reduce((sum, v) => sum + v.likes, 0),
      byType: {
        neural: list.filter(v => v.type === 'neural').length,
        matrix: list.filter(v => v.type === 'matrix').length,
        aurora: list.filter(v => v.type === 'aurora').length,
        cyber: list.filter(v => v.type === 'cyber').length,
        nature: list.filter(v => v.type === 'nature').length
      }
    };

    return { success: true, data: stats };
  }

  formatDuration(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  formatCount(num: number): string {
    if (num >= 1000000) {
      return (num / 1000000).toFixed(1) + 'M';
    }
    if (num >= 1000) {
      return (num / 1000).toFixed(1) + 'K';
    }
    return num.toString();
  }
}

export const VideoService = new VideoServiceImpl();
